<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->truncate();

        $data = [
            [
                'name'          => 'Iphone 14 Promax',
                'slug'          => 'iphone-14-promax',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0001',
                'price'         => 45000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 1,
                'author_id'     => 1,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Samsung Galaxy S23 Ultra',
                'slug'          => 'samsung-galaxy-s23-ultra',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0002',
                'price'         => 42000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 2,
                'author_id'     => 1,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Xiaomi 13 Pro',
                'slug'          => 'xiaomi-13-pro',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0003',
                'price'         => 36000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 3,
                'author_id'     => 1,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'OPPO Find X5 Pro',
                'slug'          => 'oppo-find-x5-pro',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0004',
                'price'         => 32000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 4,
                'author_id'     => 1,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Vivo V25E',
                'slug'          => 'vivo-v25e',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0005',
                'price'         => 8000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 5,
                'author_id'     => 1,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Realme 10',
                'slug'          => 'realme-10',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0006',
                'price'         => 7000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 6,
                'author_id'     => 1,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Nokia G22',
                'slug'          => 'nokia-g22',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0007',
                'price'         => 6000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 7,
                'author_id'     => 1,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Vsmart Joy 4',
                'slug'          => 'vsmart-joy-4',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0008',
                'price'         => 5000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 8,
                'author_id'     => 1,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'ASUS ROG Phone 6',
                'slug'          => 'asus-rog-phone-6',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0009',
                'price'         => 20000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 9,
                'author_id'     => 1,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Itel L6502',
                'slug'          => 'itel-l6502',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0010',
                'price'         => 2000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 10,
                'author_id'     => 1,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Iphone 13',
                'slug'          => 'iphone-13',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0011',
                'price'         => 35000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 1,
                'author_id'     => 1,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Samsung Galaxy S22',
                'slug'          => 'samsung-galaxy-s22',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0012',
                'price'         => 32000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 2,
                'author_id'     => 1,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Xiaomi 12',
                'slug'          => 'xiaomi-12',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0013',
                'price'         => 24000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 3,
                'author_id'     => 1,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'OPPO Find X4',
                'slug'          => 'oppo-find-x4',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0014',
                'price'         => 20000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 4,
                'author_id'     => 1,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Vivo V24',
                'slug'          => 'vivo-v24',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0015',
                'price'         => 6000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 5,
                'author_id'     => 1,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Nokia 8210',
                'slug'          => 'nokia-8210',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0016',
                'price'         => 500000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 7,
                'author_id'     => 2,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Nokia 215',
                'slug'          => 'nokia-215',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0017',
                'price'         => 600000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 7,
                'author_id'     => 2,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Mobell F309',
                'slug'          => 'mobell-f309',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0018',
                'price'         => 650000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 11,
                'author_id'     => 2,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Mobell Rock 4',
                'slug'          => 'mobell-rock-4',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0019',
                'price'         => 400000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 11,
                'author_id'     => 2,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Itel it9210',
                'slug'          => 'itel-it9210',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0020',
                'price'         => 300000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 12,
                'author_id'     => 2,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Acer Aspire 5 Gaming',
                'slug'          => 'acer-aspire-5-gaming',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0021',
                'price'         => 13000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 14,
                'author_id'     => 3,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Acer Aspire Lite 15',
                'slug'          => 'acer-aspire-lite-15',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0022',
                'price'         => 13000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 14,
                'author_id'     => 3,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Dell Inspiron 15',
                'slug'          => 'dell-inspiron-15',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0023',
                'price'         => 11800000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 9,
                'author_id'     => 3,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Dell Vostro 14',
                'slug'          => 'dell-vostro-14',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0024',
                'price'         => 17990000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 9,
                'author_id'     => 3,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Dell Precision 16',
                'slug'          => 'dell-precision-16',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0025',
                'price'         => 88000000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 9,
                'author_id'     => 3,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Ipad 9',
                'slug'          => 'ipad-9',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0026',
                'price'         => 7200000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 1,
                'author_id'     => 3,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'OPPO Pad Neo',
                'slug'          => 'oppo-pad-neo',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0027',
                'price'         => 6990000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 4,
                'author_id'     => 3,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Samsung Galaxy Tab A9',
                'slug'          => 'samsung-galaxy-tab-a9',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0028',
                'price'         => 6690000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 2,
                'author_id'     => 3,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Lenovo Tab M10',
                'slug'          => 'lenovo-tab-m10',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0029',
                'price'         => 5290000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 15,
                'author_id'     => 3,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'          => 'Xiaomi Redmi Pad SE',
                'slug'          => 'xiaomi-redmi-pad-se',
                'sku_prefix'    => 'PRO',
                'sku_number'    => '0030',
                'price'         => 4290000,
                'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'brand_id'      => 3,
                'author_id'     => 3,
                'created_at'    => now()->format('Y-m-d H:i:s'),
                'updated_at'    => now()->format('Y-m-d H:i:s'),
            ],
        ];

        // for ($i = 1; $i <= 30; $i++) {
        //     $data[] = [
        //         'name'          => 'smartphone ' . $i,
        //         'slug'          => 'smartphone-' . $i,
        //         'sku_prefix'    => 'PRO',
        //         'sku_number'    => '00' . (20 + $i),
        //         'price'         => 5000000,
        //         'description'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        //         'brand_id'      => null,
        //         'author_id'     => 1,
        //         'created_at'    => now()->format('Y-m-d H:i:s'),
        //         'updated_at'    => now()->format('Y-m-d H:i:s'),
        //     ];
        // }

        DB::table('products')->insert($data);
    }
}
