<?php

namespace Database\Seeders;

use App\Enums\TotalRangeType;
use Faker\Provider\Lorem;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TransportFeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('transport_fees')->truncate();

        DB::table('transport_fees')->insert([
            // GHN area ngoại tỉnh
            // GHN case normal
            [
                'name'                      => 'GiaoHangNhanh 001',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 0,
                'total_range_top_type'      => TotalRangeType::NOT_EQUAL,
                'total_range_top'           => 5000000,
                'area_id'                   => 4,
                'transporter_case_id'       => 6,
                'cost'                      => 86000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'                      => 'GiaoHangNhanh 002',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 5000000,
                'total_range_top_type'      => TotalRangeType::NOT_EQUAL,
                'total_range_top'           => 15000000,
                'area_id'                   => 4,
                'transporter_case_id'       => 6,
                'cost'                      => 46000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'                      => 'GiaoHangNhanh 003',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 15000000,
                'total_range_top_type'      => TotalRangeType::NOT_EQUAL,
                'total_range_top'           => null,
                'area_id'                   => 4,
                'transporter_case_id'       => 6,
                'cost'                      => 26000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
            // GHN case fast
            [
                'name'                      => 'GiaoHangNhanh 004',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 0,
                'total_range_top_type'      => TotalRangeType::NOT_EQUAL,
                'total_range_top'           => 5000000,
                'area_id'                   => 4,
                'transporter_case_id'       => 7,
                'cost'                      => 145000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'                      => 'GiaoHangNhanh 005',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 5000000,
                'total_range_top_type'      => TotalRangeType::NOT_EQUAL,
                'total_range_top'           => 15000000,
                'area_id'                   => 4,
                'transporter_case_id'       => 7,
                'cost'                      => 85000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'                      => 'GiaoHangNhanh 006',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 15000000,
                'total_range_top_type'      => TotalRangeType::EQUAL,
                'total_range_top'           => null,
                'area_id'                   => 4,
                'transporter_case_id'       => 7,
                'cost'                      => 45000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
            // GHN area ngoại thành
            // GHN case normal
            [
                'name'                      => 'GiaoHangNhanh 007',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 0,
                'total_range_top_type'      => TotalRangeType::NOT_EQUAL,
                'total_range_top'           => 5000000,
                'area_id'                   => 5,
                'transporter_case_id'       => 6,
                'cost'                      => 44000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'                      => 'GiaoHangNhanh 008',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 5000000,
                'total_range_top_type'      => TotalRangeType::NOT_EQUAL,
                'total_range_top'           => 15000000,
                'area_id'                   => 5,
                'transporter_case_id'       => 6,
                'cost'                      => 24000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'                      => 'GiaoHangNhanh 009',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 15000000,
                'total_range_top_type'      => TotalRangeType::EQUAL,
                'total_range_top'           => null,
                'area_id'                   => 5,
                'transporter_case_id'       => 6,
                'cost'                      => 14000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
            // GHN case fast
            [
                'name'                      => 'GiaoHangNhanh 010',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 0,
                'total_range_top_type'      => TotalRangeType::NOT_EQUAL,
                'total_range_top'           => 5000000,
                'area_id'                   => 5,
                'transporter_case_id'       => 7,
                'cost'                      => 83000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'                      => 'GiaoHangNhanh 011',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 5000000,
                'total_range_top_type'      => TotalRangeType::NOT_EQUAL,
                'total_range_top'           => 15000000,
                'area_id'                   => 5,
                'transporter_case_id'       => 7,
                'cost'                      => 43000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'                      => 'GiaoHangNhanh 012',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 15000000,
                'total_range_top_type'      => TotalRangeType::EQUAL,
                'total_range_top'           => null,
                'area_id'                   => 5,
                'transporter_case_id'       => 7,
                'cost'                      => 23000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
            // GHN area nội thành
            // GHN case normal
            [
                'name'                      => 'GiaoHangNhanh 013',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 0,
                'total_range_top_type'      => TotalRangeType::NOT_EQUAL,
                'total_range_top'           => 5000000,
                'area_id'                   => 6,
                'transporter_case_id'       => 6,
                'cost'                      => 22000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'                      => 'GiaoHangNhanh 014',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 5000000,
                'total_range_top_type'      => TotalRangeType::NOT_EQUAL,
                'total_range_top'           => 15000000,
                'area_id'                   => 6,
                'transporter_case_id'       => 6,
                'cost'                      => 12000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'                      => 'GiaoHangNhanh 015',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 15000000,
                'total_range_top_type'      => TotalRangeType::EQUAL,
                'total_range_top'           => null,
                'area_id'                   => 6,
                'transporter_case_id'       => 6,
                'cost'                      => 2000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
            // GHN case fast
            [
                'name'                      => 'GiaoHangNhanh 016',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 0,
                'total_range_top_type'      => TotalRangeType::EQUAL,
                'total_range_top'           => 5000000,
                'area_id'                   => 6,
                'transporter_case_id'       => 7,
                'cost'                      => 41000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'                      => 'GiaoHangNhanh 017',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 5000000,
                'total_range_top_type'      => TotalRangeType::NOT_EQUAL,
                'total_range_top'           => 15000000,
                'area_id'                   => 6,
                'transporter_case_id'       => 7,
                'cost'                      => 21000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'                      => 'GiaoHangNhanh 018',
                'description'               => Lorem::paragraph(3),
                'author_id'                 => 1,
                'total_range_bottom_type'   => TotalRangeType::EQUAL,
                'total_range_bottom'        => 15000000,
                'total_range_top_type'      => TotalRangeType::EQUAL,
                'total_range_top'           => null,
                'area_id'                   => 6,
                'transporter_case_id'       => 7,
                'cost'                      => 11000,
                'created_at'                => now()->format('Y-m-d H:i:s'),
                'updated_at'                => now()->format('Y-m-d H:i:s'),
            ],
        ]);
    }
}
